services:
  app:
    image: ksairos/fastapi
    ports:
      - "80:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network


  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER={$DATABASE_USERNAME}
      - POSTGRES_PASSWORD={$DATABASE_PASSWORD}
      - POSTGRES_DB={$DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: