services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres 
    env_file:
      - .env
    volumes:
      - .:/usr/src/app:ro
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network


  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER={$DATABASE_USERNAME}
      - POSTGRES_PASSWORD={$DATABASE_PASSWORD}
      - POSTGRES_DB={$DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: