"""autogenerate

Revision ID: 86e997ef90e3
Revises: a102a258f9ec
Create Date: 2025-01-14 17:31:57.489335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e997ef90e3'
down_revision: Union[str, None] = 'a102a258f9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fkey_post_owner_id', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('votes', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'user_id')
    op.drop_column('votes', 'post_id')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('fkey_post_owner_id', 'posts', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
